apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deplyment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: amaglione/client-test:latest
        ports:
        - containerPort: 3000
        env:
        - name: BASE_URL
          value: "server"
        - name: WS_URL
        # Replace value for WS_URL with the LoadBalancer IP of the server service
          value: "localhost:8081"