apiVersion: v1
kind: Service
metadata:
  name: final-sd-service
spec:
  selector:
    app: final-sd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-sd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final-sd
  template:
    metadata:
      labels:
        app: final-sd
    spec:
      containers:
      - name: final-sd
        image: amaglione/final-sd:latest
        ports:
        - containerPort: 8080
